// RootLayout.js
import { CartProvider } from '@/context/cartProvider';
import './globals.scss';

export const metadata = {
    title: "М`яке скло",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ua">
            <head>
                <link
                    href="https://cdn.jsdelivr.net/gh/Alaev-Co/snowflakes/dist/snow.min.css"
                    rel="stylesheet"
                />
            </head>
            <CartProvider>
                <body>{children}</body>
            </CartProvider>
        </html>
    );
}
