import { CartProvider } from '@/context/cartProvider';
import "./globals.scss";
import ConsentBanner from "@/components/ConsentBanner/ConsentBanner";

export const metadata = {
    title: "М`яке скло",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
            <ConsentBanner/>
            <CartProvider>
                    {children}
                </CartProvider>
            </body>
        </html>
    );
}
